stages:
  - deploy

deploy_be:
  stage: deploy
  only:
    refs:
      - staging
    changes:
      - "server/**/*"
  script:
    - git remote heroku-be-app || true
    - git remote add heroku-be-app https://heroku:$HEROKU_API_KEY@git.heroku.com/ewa-mudjeans-is201-b1-be.git || true
    - git subtree split --prefix server -b splitting-staging-be
    - git push --force heroku-be-app splitting-staging-be:master
    - git branch -D splitting-staging-be

deploy_fe:
  stage: deploy
  only:
    refs:
      - staging
    changes:
      - "client/**/*"
  script:
    - git remote rm heroku-fe-app || true
    - git remote add heroku-fe-app https://heroku:$HEROKU_API_KEY@git.heroku.com/ewa-mudjeans-is201-b1-fe.git || true
    - git subtree split --prefix client -b splitting-staging-fe
    - git push --force heroku-fe-app splitting-staging-fe:master
    - git branch -D splitting-staging-fe
